# -*- coding: utf-8 -*-
"""emp_validate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eAHJQcdMXllIwFqzZTM_d1hdgzuQu-KF
"""

import os
import pandas as pd

file_path = '/content/employees.csv'
file_size = os.path.getsize(file_path)

print(f"File size: {file_size} bytes")

df = pd.read_csv(file_path)
num_records = len(df)

print(f"Number of records: {num_records}")



# EXISTENCE ASSERTIONS

import pandas as pd

def validate_firstname(datafile):
    df = pd.read_csv(datafile)

    invalid_rows = df['name'].isna() | (df['name'].str.strip() == '')
    violation_count = invalid_rows.sum()

    print(f"Number of records with null or empty firstname: {violation_count}")
    return violation_count

if __name__ == "__main__":
    datafile = "/content/employees.csv"
    validate_firstname(datafile)

df.head(2)

import pandas as pd

def validate_hire_date(datafile):
    df = pd.read_csv(datafile)

    invalid_rows = df['hire_date'].isna() | (df['hire_date'].str.strip() == '')
    violation_count = invalid_rows.sum()

    print(f"Number of records with null or empty hire_date: {violation_count}")
    return violation_count

if __name__ == "__main__":
    datafile = "/content/employees.csv"
    print("\nValidating Assertion 0: Non-null hire_date")
    validate_hire_date(datafile)



#LIMIT ASSERTIONS

df['hire_date'] = pd.to_datetime(df['hire_date'])

invalid_hire_date_count = (df['hire_date'] < '2015-01-01').sum()
print(f"Records hired before 2015 are: {invalid_hire_date_count}")

df['salary'] = pd.to_numeric(df['salary'])

invalid_salary_count = (df['salary'] > 70000).sum()
print(f"Records with salary greater than 200000: {invalid_salary_count}")



# Intra-record Assertion

df['birth_date'] = pd.to_datetime(df['birth_date'])
df['hire_date'] = pd.to_datetime(df['hire_date'])

invalid_birth_before_hire_count = (df['birth_date'] >= df['hire_date']).sum()
print(f"Records where birth_date is greater than equal to hire_date: {invalid_birth_before_hire_count}")

df['age_at_hire'] = ((df['hire_date'] - df['birth_date']).dt.days) / 365.25

invalid_age_at_hire_count = (df['age_at_hire'] < 21).sum()
print(f"Records where employee's age is less than 18 at the time of hire: {invalid_age_at_hire_count}")



# Inter-record Assertion

invalid_manager_count = df[~df['reports_to'].isin(df['eid'])].shape[0]
print(f"Records where employee's manager is not a known employee: {invalid_manager_count}")

employees_with_no_reports = df[~df['eid'].isin(df['reports_to'])]

invalid_report_count = employees_with_no_reports.shape[0]
print(f"Records where employees have no direct reports: {invalid_report_count}")



# Summary Assertion

city_employee_counts = df['city'].value_counts()

invalid_city_count = city_employee_counts[city_employee_counts < 2].shape[0]
print(f"Records where cities have less than two employees: {invalid_city_count}")

country_employee_count = df['country'].value_counts()

invalid_country_count = country_employee_count[country_employee_count < 2].shape[0]

print(f"Number of countries with less than two employees: {invalid_country_count}")



# Statistical Assestions

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))
sns.histplot(df['salary'], kde=True, bins=20, color='blue')

plt.title('Histogram of Salaries')
plt.xlabel('Salary')
plt.ylabel('Frequency')

plt.show()

import numpy as np
import pandas as pd
from scipy.stats import chisquare

plt.figure(figsize=(10, 6))
sns.histplot(df['salary'], kde=False, bins=10, color='green')
plt.title('Salary Distribution')
plt.xlabel('Salary')
plt.ylabel('Frequency')
plt.show()

bins = 10
salary_range = df['salary'].max() - df['salary'].min()
bin_width = salary_range / bins

observed_freq, bin_edges = np.histogram(df['salary'], bins=bins)

expected_freq = [len(df) / bins] * bins

chi_stat, p_value = chisquare(f_obs=observed_freq, f_exp=expected_freq)

print(f"Chi-square Statistic: {chi_stat:.2f}")
print(f"P-value: {p_value:.4f}")

if p_value > 0.05:
    print("The salaries are uniformly distributed.")
else:
    print("The salaries are not uniformly distributed.")