# -*- coding: utf-8 -*-
"""Data_Transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uK0p8NTH3z4AkG7i-0kZS4GprZFwVMVS
"""

pip install pandas

import pandas as pd

file_path = '/content/bc_trip259172515_230215.csv'
df = pd.read_csv(file_path)

breadcrumb_count = len(df)

print(f"The dataset contains {breadcrumb_count} breadcrumb records.")

import pandas as pd

file_path = '/content/bc_trip259172515_230215.csv'
df = pd.read_csv(file_path)

df_filtered = df.drop(columns=['EVENT_NO_STOP', 'GPS_HDOP'])

print(df_filtered.head())

import pandas as pd

cols_to_keep = ['EVENT_NO_TRIP', 'OPD_DATE', 'VEHICLE_ID','METERS','ACT_TIME','GPS_LONGITUDE','GPS_LATITUDE','GPS_SATELLITES']  # Replace with actual column names you want to keep
df_filtered_usecols = pd.read_csv(file_path, usecols=cols_to_keep)

print(df_filtered_usecols.head())

import pandas as pd

file_path = '/content/bc_trip259172515_230215.csv'
df = pd.read_csv(file_path)

df['OPD_DATE'] = pd.to_datetime(df['OPD_DATE'], format='%d%b%Y:%H:%M:%S')

df['TIMESTAMP'] = df['OPD_DATE'] + pd.to_timedelta(df['ACT_TIME'], unit='s')

print(df[['OPD_DATE', 'ACT_TIME', 'TIMESTAMP']].head())

import pandas as pd

file_path = '/content/bc_trip259172515_230215.csv'
df = pd.read_csv(file_path)

def decode_timestamp(row):
    opd_date = pd.to_datetime(row['OPD_DATE'], format='%d%b%Y:%H:%M:%S')
    act_time = pd.to_timedelta(row['ACT_TIME'], unit='s')
    return opd_date + act_time

df['TIMESTAMP'] = df.apply(decode_timestamp, axis=1)

df.drop(columns=['OPD_DATE', 'ACT_TIME'], inplace=True)

print("Remaining columns after filtering:", df.columns)
print(df.head())

import pandas as pd

file_path = '/content/bc_trip259172515_230215.csv'
df = pd.read_csv(file_path)

df['OPD_DATE'] = pd.to_datetime(df['OPD_DATE'], format='%d%b%Y:%H:%M:%S')
df['ACT_TIME'] = pd.to_timedelta(df['ACT_TIME'], unit='s')
df['TIMESTAMP'] = df['OPD_DATE'] + df['ACT_TIME']

df.drop(columns=['OPD_DATE', 'ACT_TIME'], inplace=True)

df['dMETERS'] = df['METERS'].diff()
df['dTIMESTAMP'] = df['TIMESTAMP'].diff().dt.total_seconds()

df['SPEED'] = df.apply(lambda row: row['dMETERS'] / row['dTIMESTAMP'] if row['dTIMESTAMP'] != 0 else None, axis=1)

df.drop(columns=['dMETERS', 'dTIMESTAMP'], inplace=True)

min_speed = df['SPEED'].min()
max_speed = df['SPEED'].max()
avg_speed = df['SPEED'].mean()

print(f"Minimum Speed: {min_speed} meters per second")
print(f"Maximum Speed: {max_speed} meters per second")
print(f"Average Speed: {avg_speed} meters per second")

import pandas as pd

df = pd.read_csv('/content/bc_veh4223_230215.csv')

df = df[df['VEHICLE_ID'] == 4223]

df['OPD_DATE'] = pd.to_datetime(df['OPD_DATE'], format='%d%b%Y:%H:%M:%S')
df['ACT_TIME'] = pd.to_timedelta(df['ACT_TIME'], unit='s')

df['TIMESTAMP'] = df['OPD_DATE'] + df['ACT_TIME']

df['dMETERS'] = df['METERS'].diff()
df['dTIMESTAMP'] = (df['TIMESTAMP'].diff()).dt.total_seconds()

df['SPEED'] = df['dMETERS'] / df['dTIMESTAMP']

df.drop(['OPD_DATE', 'ACT_TIME', 'dMETERS', 'dTIMESTAMP'], axis=1, inplace=True)

max_speed_row = df.loc[df['SPEED'].idxmax()]
max_speed = max_speed_row['SPEED']
max_speed_time = max_speed_row['TIMESTAMP']
max_speed_location = (max_speed_row['GPS_LATITUDE'], max_speed_row['GPS_LONGITUDE'])

median_speed = df['SPEED'].median()

print(f"Maximum Speed: {max_speed} m/s")
print(f"Maximum Speed Occurred at: {max_speed_time}")
print(f"Location of Maximum Speed: Latitude = {max_speed_location[0]}, Longitude = {max_speed_location[1]}")
print(f"Median Speed: {median_speed} m/s")