# -*- coding: utf-8 -*-
"""Data_Integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYMm2x5bKWg7uaRCyUc-ewfvNWTpGD0p
"""

import pandas as pd

cases_df = pd.read_csv('/content/covid_confirmed_usafacts.csv')
deaths_df = pd.read_csv('/content/covid_deaths_usafacts.csv')
census_df = pd.read_csv('/content/acs2017_county_data.csv')

print("COVID Cases Columns:", cases_df.columns.tolist())
print("COVID Deaths Columns:", deaths_df.columns.tolist())
print("Census Columns:", census_df.columns.tolist())

# 1.

date_columns = [col for col in cases_df.columns if col not in ['countyFIPS', 'County Name', 'State', 'StateFIPS']]

cases_df['Cases'] = cases_df[date_columns].sum(axis=1)
deaths_df['Deaths'] = deaths_df[date_columns].sum(axis=1)

cases_df = cases_df[['countyFIPS', 'County Name', 'State', 'Cases']]
deaths_df = deaths_df[['countyFIPS', 'County Name', 'State', 'Deaths']]

census_df = census_df.rename(columns={
    'County': 'County Name',
    'CountyId': 'countyFIPS'
})

census_df = census_df[['countyFIPS', 'County Name', 'State', 'TotalPop',
                       'IncomePerCap', 'Poverty', 'Unemployment']]

def standardize_name(name):
    return name.lower().replace("county", "").replace("parish", "").strip()

cases_df['County Name'] = cases_df['County Name'].apply(standardize_name)
deaths_df['County Name'] = deaths_df['County Name'].apply(standardize_name)
census_df['County Name'] = census_df['County Name'].apply(standardize_name)

merged_df = cases_df.merge(deaths_df, on=['countyFIPS', 'State'], how='inner')
merged_df = merged_df.merge(census_df, on=['countyFIPS', 'State'], how='inner')

merged_df['CasesPerCap'] = merged_df['Cases'] / merged_df['TotalPop']
merged_df['DeathsPerCap'] = merged_df['Deaths'] / merged_df['TotalPop']

final_df = merged_df[[
    'County Name', 'State', 'Cases', 'Deaths', 'CasesPerCap',
    'DeathsPerCap', 'TotalPop', 'IncomePerCap', 'Poverty', 'Unemployment'
]]

final_df = final_df.dropna(subset=['Cases', 'Deaths', 'TotalPop'])
final_df = final_df.astype({
    'Cases': 'int',
    'Deaths': 'int',
    'TotalPop': 'int',
    'CasesPerCap': 'float',
    'DeathsPerCap': 'float',
    'IncomePerCap': 'float',
    'Poverty': 'float',
    'Unemployment': 'float'
})

final_df.to_csv('integrated_covid_census.csv', index=False)
print(final_df.head())

# 2.

print("Cases DataFrame:")
print(cases_df.head())
print("\nDeaths DataFrame:")
print(deaths_df.head())
print("\nCensus DataFrame:")
print(census_df.head())

cases_df = cases_df[['County Name', 'State', '2023-07-23']]
deaths_df = deaths_df[['County Name', 'State', '2023-07-23']]

print("Trimmed Cases:")
print(cases_df.head())
print("\nTrimmed Deaths:")
print(deaths_df.head())

census_df = census_df[['County', 'State', 'TotalPop', 'IncomePerCap', 'Poverty', 'Unemployment']]
print("Trimmed cases for census data:")
print(census_df.head())

# 3.

cases_df['County Name'] = cases_df['County Name'].str.strip()
deaths_df['County Name'] = deaths_df['County Name'].str.strip()

print("Trimmed and Cleaned Cases DataFrame:")
print(cases_df.head())
print("\nTrimmed and Cleaned Deaths DataFrame:")
print(deaths_df.head())

cases_washington = cases_df[cases_df['County Name'] == 'Washington County']
deaths_washington = deaths_df[deaths_df['County Name'] == 'Washington County']
print(cases_washington)
print(deaths_washington)

print("Remaining rows in cases_df:", cases_df.shape[0])
print("Remaining rows in deaths_df:", deaths_df.shape[0])

# 4.

cases_df = cases_df[cases_df['County Name'] != 'Statewide Unallocated']
deaths_df = deaths_df[deaths_df['County Name'] != 'Statewide Unallocated']
print(cases_df)
print(deaths_df)

print("Remaining rows in cases_df:", cases_df.shape[0])
print("Remaining rows in deaths_df:", deaths_df.shape[0])

# 5.

us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "Virgin Islands, U.S.": "VI",
}

abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))

# Clean and map abbreviations to full names
cases_df['State'] = cases_df['State'].str.strip().str.upper().map(abbrev_to_us_state)
deaths_df['State'] = deaths_df['State'].str.strip().str.upper().map(abbrev_to_us_state)

# Display the result
print("cases_df:")
print(cases_df.head())

print("deaths_df:")
print(deaths_df.head())

# 6.

cases_df['key'] = cases_df['County Name'].str.strip() + ', ' + cases_df['State'].str.strip()
cases_df.set_index('key', inplace=True)

deaths_df['key'] = deaths_df['County Name'].str.strip() + ', ' + deaths_df['State'].str.strip()
deaths_df.set_index('key', inplace=True)

census_df['key'] = census_df['County'].str.strip() + ', ' + census_df['State'].str.strip()
census_df.set_index('key', inplace=True)

print("census_df:")
print(census_df.head())

# 7.

cases_df = cases_df.rename(columns={'2023-07-23': 'Cases'})
deaths_df = deaths_df.rename(columns={'2023-07-23': 'Deaths'})
print(cases_df.head())
print(deaths_df.head())

cases_df.columns.values.tolist()

deaths_df.columns.values.tolist()

# 8.

join_df = census_df.join(cases_df, how='inner', lsuffix='_census', rsuffix='_cases')

join_df = join_df.join(deaths_df, how='inner', rsuffix='_deaths')

join_df['TotalPop'] = pd.to_numeric(join_df['TotalPop'], errors='coerce')

case_col = [col for col in join_df.columns if col.endswith('_cases')][0]
death_col = [col for col in join_df.columns if col.endswith('_deaths')][0]

join_df[case_col] = pd.to_numeric(join_df[case_col], errors='coerce')
join_df[death_col] = pd.to_numeric(join_df[death_col], errors='coerce')

join_df['CasesPerCap'] = join_df[case_col] / join_df['TotalPop']
join_df['DeathsPerCap'] = join_df[death_col] / join_df['TotalPop']

print("Number of rows in join_df:", join_df.shape[0])

correlation_matrix = join_df.corr(numeric_only=True)

print(correlation_matrix)

import seaborn as sns
import matplotlib.pyplot as plt

# Generate the correlation matrix among numeric columns
correlation_matrix = join_df.corr(numeric_only=True)

# Create a heatmap to visualize the correlation matrix
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)

# Add a title to the heatmap
plt.title('Correlation Matrix Heatmap')

# Display the heatmap
plt.show()

