# -*- coding: utf-8 -*-
"""Publisher_Data_Transportation_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqCb3vpQ4Pv7cz_OAzW0E6-JH57SP2LO
"""

from google.cloud import pubsub_v1
import json
project_id = "dataengineeringproject-456307"
topic_id = "MyTopic"

publisher = pubsub_v1.PublisherClient()
topic_path = publisher.topic_path(project_id, topic_id)

def publish_message(data):
    future = publisher.publish(topic_path, data.encode("utf-8"))
    print(f"Published message: {data}")

with open("bcsample.json","r") as json_file:
    records = json.load(json_file)
    for record in records:
        publish_message(json.dumps(record))

print(f"Published messages to {topic_path}.")

