# -*- coding: utf-8 -*-
"""Subscriber_Data_Transportation_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3_QO8qttO3mLMQ-IW9JNSbc7PhQwmtI
"""

from google.cloud import pubsub_v1

project_id = "dataengineeringproject-456307"
subscription_id = "MySub"

subscriber = pubsub_v1.SubscriberClient()
subscription_path = subscriber.subscription_path(project_id, subscription_id)

message_count = 0

def callback(message):
    global message_count
    message_count += 1
    message.ack()

streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)
print(f"Listening on {subscription_path}...")

try:
    streaming_pull_future.result(timeout=10)
except Exception:
    streaming_pull_future.cancel()

print(f"Total messages received: {message_count}")